# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: zservice/zservice.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import zservice.zservice_pb2 as zservice_dot_zservice__pb2


class SoService(Protocol):
    async def get_ifm(self, request: zservice_dot_zservice__pb2.GetIfmReq, ctx: RequestContext) -> zservice_dot_zservice__pb2.GetIfmResp:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SoServiceASGIApplication(ConnectASGIApplication[SoService]):
    def __init__(self, service: SoService | AsyncGenerator[SoService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/so.v1.SoService/GetIfm": Endpoint.unary(
                    method=MethodInfo(
                        name="GetIfm",
                        service_name="so.v1.SoService",
                        input=zservice_dot_zservice__pb2.GetIfmReq,
                        output=zservice_dot_zservice__pb2.GetIfmResp,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_ifm,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/so.v1.SoService"


class SoServiceClient(ConnectClient):
    async def get_ifm(
        self,
        request: zservice_dot_zservice__pb2.GetIfmReq,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> zservice_dot_zservice__pb2.GetIfmResp:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetIfm",
                service_name="so.v1.SoService",
                input=zservice_dot_zservice__pb2.GetIfmReq,
                output=zservice_dot_zservice__pb2.GetIfmResp,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class SoServiceSync(Protocol):
    def get_ifm(self, request: zservice_dot_zservice__pb2.GetIfmReq, ctx: RequestContext) -> zservice_dot_zservice__pb2.GetIfmResp:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SoServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: SoServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/so.v1.SoService/GetIfm": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetIfm",
                        service_name="so.v1.SoService",
                        input=zservice_dot_zservice__pb2.GetIfmReq,
                        output=zservice_dot_zservice__pb2.GetIfmResp,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_ifm,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/so.v1.SoService"


class SoServiceClientSync(ConnectClientSync):
    def get_ifm(
        self,
        request: zservice_dot_zservice__pb2.GetIfmReq,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> zservice_dot_zservice__pb2.GetIfmResp:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetIfm",
                service_name="so.v1.SoService",
                input=zservice_dot_zservice__pb2.GetIfmReq,
                output=zservice_dot_zservice__pb2.GetIfmResp,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


