# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zservice/zservice.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'zservice/zservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17zservice/zservice.proto\x12\x05so.v1\"z\n\tGetIfmReq\x12\x34\n\x08messages\x18\x01 \x03(\x0b\x32\x18.so.v1.GetIfmReq.MsgItemR\x08messages\x1a\x37\n\x07MsgItem\x12\x12\n\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n\x07\x63ontent\x18\x02 \x01(\tR\x07\x63ontent\"\xc4\x01\n\nGetIfmResp\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n\x05model\x18\x04 \x01(\tR\x05model\x12\x35\n\x08messages\x18\x63 \x03(\x0b\x32\x19.so.v1.GetIfmResp.MsgItemR\x08messages\x1a\x31\n\x07MsgItem\x12\x12\n\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n\x04text\x18\x02 \x01(\tR\x04text2<\n\tSoService\x12/\n\x06GetIfm\x12\x10.so.v1.GetIfmReq\x1a\x11.so.v1.GetIfmResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zservice.zservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETIFMREQ']._serialized_start=34
  _globals['_GETIFMREQ']._serialized_end=156
  _globals['_GETIFMREQ_MSGITEM']._serialized_start=101
  _globals['_GETIFMREQ_MSGITEM']._serialized_end=156
  _globals['_GETIFMRESP']._serialized_start=159
  _globals['_GETIFMRESP']._serialized_end=355
  _globals['_GETIFMRESP_MSGITEM']._serialized_start=306
  _globals['_GETIFMRESP_MSGITEM']._serialized_end=355
  _globals['_SOSERVICE']._serialized_start=357
  _globals['_SOSERVICE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
