# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: session/session.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import session.session_pb2 as session_dot_session__pb2


class SessionService(Protocol):
    async def get_session(self, request: session_dot_session__pb2.GetSessionReq, ctx: RequestContext) -> session_dot_session__pb2.GetSessionResp:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SessionServiceASGIApplication(ConnectASGIApplication[SessionService]):
    def __init__(self, service: SessionService | AsyncGenerator[SessionService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/session.v1.SessionService/GetSession": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSession",
                        service_name="session.v1.SessionService",
                        input=session_dot_session__pb2.GetSessionReq,
                        output=session_dot_session__pb2.GetSessionResp,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_session,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/session.v1.SessionService"


class SessionServiceClient(ConnectClient):
    async def get_session(
        self,
        request: session_dot_session__pb2.GetSessionReq,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> session_dot_session__pb2.GetSessionResp:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSession",
                service_name="session.v1.SessionService",
                input=session_dot_session__pb2.GetSessionReq,
                output=session_dot_session__pb2.GetSessionResp,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class SessionServiceSync(Protocol):
    def get_session(self, request: session_dot_session__pb2.GetSessionReq, ctx: RequestContext) -> session_dot_session__pb2.GetSessionResp:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SessionServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: SessionServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/session.v1.SessionService/GetSession": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSession",
                        service_name="session.v1.SessionService",
                        input=session_dot_session__pb2.GetSessionReq,
                        output=session_dot_session__pb2.GetSessionResp,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_session,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/session.v1.SessionService"


class SessionServiceClientSync(ConnectClientSync):
    def get_session(
        self,
        request: session_dot_session__pb2.GetSessionReq,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> session_dot_session__pb2.GetSessionResp:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSession",
                service_name="session.v1.SessionService",
                input=session_dot_session__pb2.GetSessionReq,
                output=session_dot_session__pb2.GetSessionResp,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


