# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session/session.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'session/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15session/session.proto\x12\nsession.v1\"(\n\rGetSessionReq\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId\"&\n\x0eGetSessionResp\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token2W\n\x0eSessionService\x12\x45\n\nGetSession\x12\x19.session.v1.GetSessionReq\x1a\x1a.session.v1.GetSessionResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSESSIONREQ']._serialized_start=37
  _globals['_GETSESSIONREQ']._serialized_end=77
  _globals['_GETSESSIONRESP']._serialized_start=79
  _globals['_GETSESSIONRESP']._serialized_end=117
  _globals['_SESSIONSERVICE']._serialized_start=119
  _globals['_SESSIONSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
